### ISSUE TITLE
Final killcam will sometimes crash the server and clients

### ISSUE THREAD

**Issue by Bobbyperson** [Bobbyperson/InfectionRework#7]
~~Randomly, the final killcam will crash the server. It's disabled because of this, but it'd be nice to have it in a working state.~~

~~Current hypothesis is these crashes are caused when the world is the killer.~~

It seems like the server crashing has been fixed, but client crashing still happens

**Comment by Bobbyperson** [comment]
https://github.com/user-attachments/assets/b8120658-7439-4c59-a6b3-f6133f8e8c47
It'll also crash clients sometimes

**Comment by Jan200101** [comment]
regarding client crash:

Quick summary on how this script error happens

- cl_screenfade does various checks
- if player is between 85% and 55% health attempt to player sound layer 2 
- `GetPainSound(localPlayer, "sound_pain_layer2_start")` is called
- query `sound_pain_layer2_start` from the character settings
- for some reason either the player is not valid or variable not found in character settings
    - the variable that tracks if layer 2 should be playing is rechecked and reset every time in the loop, if the player isn't valid or dead it never marks layer 2 as to be played
- EmitSoundOnEntity is called with empty string
- Script error

I'm not entirely sure why this happens but its possible that something is changing the player character to something invalid 

The code that crashes looks like [this](https://github.com/Syampuuh/Titanfall2-orig/blob/9e57b224ae7df25f61b1f44a0dcb7dea705fbd2b/vscripts/client/cl_screenfade.gnut#L248-L251)
```nut
				soundLayer2Start = GetPainSound( ourPlayer, "sound_pain_layer2_start" )
				soundLayer2Loop = GetPainSound( ourPlayer, "sound_pain_layer2_loop" )
				EmitSoundOnEntity( ourPlayer, soundLayer2Start )
				EmitSoundOnEntity( ourPlayer, soundLayer2Loop )
```

adding a sanity check, like how its done in soundLayer1 will fix the issue

```nut
				soundLayer2Start = GetPainSound( ourPlayer, "sound_pain_layer2_start" )
				soundLayer2Loop = GetPainSound( ourPlayer, "sound_pain_layer2_loop" )

				if ( soundLayer2Start != "" )
					EmitSoundOnEntity( ourPlayer, soundLayer2Start )
				if ( soundLayer2Loop != "" )
					EmitSoundOnEntity( ourPlayer, soundLayer2Loop )
```

soundLayer3 is affected by the same issue and should be updated in a similar way

`cl_screenfade.gnut` has not been imported into Northstar-Mods and needs to be imported from the base game [cl_screenfade.gnut](https://github.com/Syampuuh/Titanfall2-orig/blob/9e57b224ae7df25f61b1f44a0dcb7dea705fbd2b/vscripts/client/cl_screenfade.gnut)

**Comment by Bobbyperson** [comment]
This issue will be solved by the PR mentioned above, will close when merged. Thank you for the detailed explanation ur so awesome
